name: Clean

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: 清理工作流运行记录
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: -1
          keep_minimum_runs: -1

      - name: 清理版本发布记录
        if: always()
        uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: -1
          pre-release-drop: true
          pre-release-keep-count: -1

      - name: 清理 GHCR 镜像仓库
        if: always()
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-untagged: -1
          keep-n-tagged: -1
